name: CD - Build and Push Docker Image

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CI requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker --quiet us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fraud-api/fraud-detection-api:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fraud-api/fraud-detection-api:${{ github.sha }}

      - name: CML Report
        env:
          REPO_TOKEN: ${{ github.token }}
        run: |
          echo "## ðŸš€ Docker Image Built & Pushed" > report.md
          echo "- Image tag: ${{ github.sha }}" >> report.md
          cml comment create report.md
